- name : Installing Docker on remote EC2 machine using trust-relationship connection
  hosts : all
  become: true
  connection : ssh
  tasks : 
  - name: apt update
    command : sudo apt-get update

  - name : Docker install
    command : sudo apt-get install -y docker.io

  - name : Start Docker service
    command : sudo systemctl start docker

